# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-prompt", "~> 0.23.0"

gem "json", "~> 2.5"

gem "colorize", "~> 0.8.1"

gem "mailjet", "~> 1.6"

gem "dotenv", "~> 2.7"
